swarm1:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc

swarm2:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc

swarm3:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc
