swarm_node_1:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc
    privileged: true
    volumes:
      - ./:/izgnod
    working_dir: /izgnod

swarm_node_2:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc
    privileged: true
    volumes:
      - ./:/izgnod
    working_dir: /izgnod

swarm_manager:
    image: izgnod/docker_in_docker_swarm:0.2
    env_file: ./.bashrc
    privileged: true
    volumes:
      - ./:/izgnod
    working_dir: /izgnod
